 
     
name: ZactechRDP
 
on: workflow_dispatch
 
jobs:
 
  build:
 
    runs-on: windows-latest
 
    timeout-minutes: 99999999
 
    steps:
 
    - name: Download Ngrok.
 
      run: |
        Invoke-WebRequest https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-windows-amd64.zip -OutFile ngrok.zip
        Invoke-WebRequest https://raw.githubusercontent.com/Zakybotz/Rdp-Free/master/start.bat -OutFile start.bat
        Invoke-WebRequest https://raw.githubusercontent.com/Zakybotz/Rdp-Free/master/wallpaper.bat -OutFile wallpaper.bat
        Invoke-WebRequest https://raw.githubusercontent.com/Zakybotz/Rdp-Free/master/loop.bat -OutFile loop.bat
        Invoke-WebRequest https://raw.githubusercontent.com/Zakybotz/Rdp-Free/master/start.bat -OutFile push.bat
    - name: Extract Ngrok File.
 
      run: Expand-Archive ngrok.zip
 
    - name: Connect Ngrok.
 
      run: .\ngrok\ngrok.exe authtoken $Env:NGROK_AUTH_TOKEN
 
      env:
 
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
 
    - name: Windows10 RDP.
 
      run: |
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
        copy wallpaper.bat D:\a\wallpaper.bat
    - name: Tunnel.
 
      run: Start-Process Powershell -ArgumentList '-Noexit -Command ".\ngrok\ngrok.exe tcp --region ap 3389"'
 
    - name: Connect RDP.
 
      run: cmd /c start.bat
 
    - name: win10 RDP.
 
      run: cmd /c loop.bat
Add Comment
Please, Sign In to add comment
Public Pastes
Урок 6 Измеряем и ускоряем
C++ | 12 sec ago | 2.71 KB
Nếu Anh Là Em Nếu Anh Là Em - Tóc Tiên, Hứa...
HTML 5 | 13 min ago | 1.82 KB
Control Block
Lua | 17 min ago | 1.72 KB
WSS
YAML | 17 min ago | 2.34 KB
Untitled
YAML | 31 min ago | 0.75 KB
How add new WordPress admin via phpmyadmin
Bash | 47 min ago | 0.73 KB
power
C | 1 hour ago | 0.71 KB
How disable 2FA in CyberPanel
Bash | 1 hour ago | 0.25 KB

create new paste  /  syntax languages  /  archive  /  faq  /  tools  /  night mode  /  api  /  scraping api  /  news  /  pro
privacy statement  /  cookies policy  /  terms of serviceupdated  /  security disclosure  /  dmca  /  report abuse  /  contact

By using Pastebin.com you agree to our cookies policy to enhance your experience.
Site design & logo © 2022 Pastebin
We use cookies for various purposes including analytics. By continuing to use Pastebin, you agree to our use of cookies as described in the Cookies Policy.  OK, I Understand
Not a member of Pastebin yet?
Sign Up, it unlocks many cool features! 
